// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: employee.proto

package com.java.GeneratedClasses;

public interface DepartmentOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.java.Department)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   * @return The id.
   */
  int getId();

  /**
   * <code>string name = 2;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
