// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: employee.proto

package com.java.GeneratedClasses;

/**
 * Protobuf type {@code com.java.Employee}
 */
public final class Employee extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.java.Employee)
    EmployeeOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Employee.newBuilder() to construct.
  private Employee(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Employee() {
    name_ = "";
    department_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Employee();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Employee(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            id_ = input.readInt32();
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            name_ = s;
            break;
          }
          case 25: {

            salary_ = input.readDouble();
            break;
          }
          case 34: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              department_ = new java.util.ArrayList<com.java.GeneratedClasses.Department>();
              mutable_bitField0_ |= 0x00000001;
            }
            department_.add(
                input.readMessage(com.java.GeneratedClasses.Department.parser(), extensionRegistry));
            break;
          }
          case 42: {
            if (!((mutable_bitField0_ & 0x00000002) != 0)) {
              addressmap_ = com.google.protobuf.MapField.newMapField(
                  AddressmapDefaultEntryHolder.defaultEntry);
              mutable_bitField0_ |= 0x00000002;
            }
            com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
            addressmap__ = input.readMessage(
                AddressmapDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
            addressmap_.getMutableMap().put(
                addressmap__.getKey(), addressmap__.getValue());
            break;
          }
          case 48: {

            inactive_ = input.readBool();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        department_ = java.util.Collections.unmodifiableList(department_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.java.GeneratedClasses.EmployeeProto.internal_static_com_java_Employee_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  @java.lang.Override
  protected com.google.protobuf.MapField internalGetMapField(
      int number) {
    switch (number) {
      case 5:
        return internalGetAddressmap();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.java.GeneratedClasses.EmployeeProto.internal_static_com_java_Employee_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.java.GeneratedClasses.Employee.class, com.java.GeneratedClasses.Employee.Builder.class);
  }

  public static final int ID_FIELD_NUMBER = 1;
  private int id_;
  /**
   * <code>int32 id = 1;</code>
   * @return The id.
   */
  @java.lang.Override
  public int getId() {
    return id_;
  }

  public static final int NAME_FIELD_NUMBER = 2;
  private volatile java.lang.Object name_;
  /**
   * <code>string name = 2;</code>
   * @return The name.
   */
  @java.lang.Override
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SALARY_FIELD_NUMBER = 3;
  private double salary_;
  /**
   * <code>double salary = 3;</code>
   * @return The salary.
   */
  @java.lang.Override
  public double getSalary() {
    return salary_;
  }

  public static final int DEPARTMENT_FIELD_NUMBER = 4;
  private java.util.List<com.java.GeneratedClasses.Department> department_;
  /**
   * <code>repeated .com.java.Department department = 4;</code>
   */
  @java.lang.Override
  public java.util.List<com.java.GeneratedClasses.Department> getDepartmentList() {
    return department_;
  }
  /**
   * <code>repeated .com.java.Department department = 4;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.java.GeneratedClasses.DepartmentOrBuilder> 
      getDepartmentOrBuilderList() {
    return department_;
  }
  /**
   * <code>repeated .com.java.Department department = 4;</code>
   */
  @java.lang.Override
  public int getDepartmentCount() {
    return department_.size();
  }
  /**
   * <code>repeated .com.java.Department department = 4;</code>
   */
  @java.lang.Override
  public com.java.GeneratedClasses.Department getDepartment(int index) {
    return department_.get(index);
  }
  /**
   * <code>repeated .com.java.Department department = 4;</code>
   */
  @java.lang.Override
  public com.java.GeneratedClasses.DepartmentOrBuilder getDepartmentOrBuilder(
      int index) {
    return department_.get(index);
  }

  public static final int ADDRESSMAP_FIELD_NUMBER = 5;
  private static final class AddressmapDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.String, java.lang.String> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.String, java.lang.String>newDefaultInstance(
                com.java.GeneratedClasses.EmployeeProto.internal_static_com_java_Employee_AddressmapEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.STRING,
                "");
  }
  private com.google.protobuf.MapField<
      java.lang.String, java.lang.String> addressmap_;
  private com.google.protobuf.MapField<java.lang.String, java.lang.String>
  internalGetAddressmap() {
    if (addressmap_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          AddressmapDefaultEntryHolder.defaultEntry);
    }
    return addressmap_;
  }

  public int getAddressmapCount() {
    return internalGetAddressmap().getMap().size();
  }
  /**
   * <code>map&lt;string, string&gt; addressmap = 5;</code>
   */

  @java.lang.Override
  public boolean containsAddressmap(
      java.lang.String key) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    return internalGetAddressmap().getMap().containsKey(key);
  }
  /**
   * Use {@link #getAddressmapMap()} instead.
   */
  @java.lang.Override
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, java.lang.String> getAddressmap() {
    return getAddressmapMap();
  }
  /**
   * <code>map&lt;string, string&gt; addressmap = 5;</code>
   */
  @java.lang.Override

  public java.util.Map<java.lang.String, java.lang.String> getAddressmapMap() {
    return internalGetAddressmap().getMap();
  }
  /**
   * <code>map&lt;string, string&gt; addressmap = 5;</code>
   */
  @java.lang.Override

  public java.lang.String getAddressmapOrDefault(
      java.lang.String key,
      java.lang.String defaultValue) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    java.util.Map<java.lang.String, java.lang.String> map =
        internalGetAddressmap().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <code>map&lt;string, string&gt; addressmap = 5;</code>
   */
  @java.lang.Override

  public java.lang.String getAddressmapOrThrow(
      java.lang.String key) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    java.util.Map<java.lang.String, java.lang.String> map =
        internalGetAddressmap().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  public static final int INACTIVE_FIELD_NUMBER = 6;
  private boolean inactive_;
  /**
   * <pre>
   *bytes profilePicture=7;
   *google.protobuf.Timestamp joindate=8;
   * </pre>
   *
   * <code>bool inactive = 6;</code>
   * @return The inactive.
   */
  @java.lang.Override
  public boolean getInactive() {
    return inactive_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (id_ != 0) {
      output.writeInt32(1, id_);
    }
    if (!getNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
    }
    if (salary_ != 0D) {
      output.writeDouble(3, salary_);
    }
    for (int i = 0; i < department_.size(); i++) {
      output.writeMessage(4, department_.get(i));
    }
    com.google.protobuf.GeneratedMessageV3
      .serializeStringMapTo(
        output,
        internalGetAddressmap(),
        AddressmapDefaultEntryHolder.defaultEntry,
        5);
    if (inactive_ != false) {
      output.writeBool(6, inactive_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (id_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, id_);
    }
    if (!getNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
    }
    if (salary_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(3, salary_);
    }
    for (int i = 0; i < department_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, department_.get(i));
    }
    for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
         : internalGetAddressmap().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
      addressmap__ = AddressmapDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, addressmap__);
    }
    if (inactive_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(6, inactive_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.java.GeneratedClasses.Employee)) {
      return super.equals(obj);
    }
    com.java.GeneratedClasses.Employee other = (com.java.GeneratedClasses.Employee) obj;

    if (getId()
        != other.getId()) return false;
    if (!getName()
        .equals(other.getName())) return false;
    if (java.lang.Double.doubleToLongBits(getSalary())
        != java.lang.Double.doubleToLongBits(
            other.getSalary())) return false;
    if (!getDepartmentList()
        .equals(other.getDepartmentList())) return false;
    if (!internalGetAddressmap().equals(
        other.internalGetAddressmap())) return false;
    if (getInactive()
        != other.getInactive()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId();
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    hash = (37 * hash) + SALARY_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getSalary()));
    if (getDepartmentCount() > 0) {
      hash = (37 * hash) + DEPARTMENT_FIELD_NUMBER;
      hash = (53 * hash) + getDepartmentList().hashCode();
    }
    if (!internalGetAddressmap().getMap().isEmpty()) {
      hash = (37 * hash) + ADDRESSMAP_FIELD_NUMBER;
      hash = (53 * hash) + internalGetAddressmap().hashCode();
    }
    hash = (37 * hash) + INACTIVE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getInactive());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.java.GeneratedClasses.Employee parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.java.GeneratedClasses.Employee parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.java.GeneratedClasses.Employee parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.java.GeneratedClasses.Employee parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.java.GeneratedClasses.Employee parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.java.GeneratedClasses.Employee parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.java.GeneratedClasses.Employee parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.java.GeneratedClasses.Employee parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.java.GeneratedClasses.Employee parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.java.GeneratedClasses.Employee parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.java.GeneratedClasses.Employee parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.java.GeneratedClasses.Employee parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.java.GeneratedClasses.Employee prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.java.Employee}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.java.Employee)
      com.java.GeneratedClasses.EmployeeOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.java.GeneratedClasses.EmployeeProto.internal_static_com_java_Employee_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 5:
          return internalGetAddressmap();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMutableMapField(
        int number) {
      switch (number) {
        case 5:
          return internalGetMutableAddressmap();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.java.GeneratedClasses.EmployeeProto.internal_static_com_java_Employee_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.java.GeneratedClasses.Employee.class, com.java.GeneratedClasses.Employee.Builder.class);
    }

    // Construct using com.java.GeneratedClasses.Employee.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getDepartmentFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      id_ = 0;

      name_ = "";

      salary_ = 0D;

      if (departmentBuilder_ == null) {
        department_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        departmentBuilder_.clear();
      }
      internalGetMutableAddressmap().clear();
      inactive_ = false;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.java.GeneratedClasses.EmployeeProto.internal_static_com_java_Employee_descriptor;
    }

    @java.lang.Override
    public com.java.GeneratedClasses.Employee getDefaultInstanceForType() {
      return com.java.GeneratedClasses.Employee.getDefaultInstance();
    }

    @java.lang.Override
    public com.java.GeneratedClasses.Employee build() {
      com.java.GeneratedClasses.Employee result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.java.GeneratedClasses.Employee buildPartial() {
      com.java.GeneratedClasses.Employee result = new com.java.GeneratedClasses.Employee(this);
      int from_bitField0_ = bitField0_;
      result.id_ = id_;
      result.name_ = name_;
      result.salary_ = salary_;
      if (departmentBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          department_ = java.util.Collections.unmodifiableList(department_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.department_ = department_;
      } else {
        result.department_ = departmentBuilder_.build();
      }
      result.addressmap_ = internalGetAddressmap();
      result.addressmap_.makeImmutable();
      result.inactive_ = inactive_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.java.GeneratedClasses.Employee) {
        return mergeFrom((com.java.GeneratedClasses.Employee)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.java.GeneratedClasses.Employee other) {
      if (other == com.java.GeneratedClasses.Employee.getDefaultInstance()) return this;
      if (other.getId() != 0) {
        setId(other.getId());
      }
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        onChanged();
      }
      if (other.getSalary() != 0D) {
        setSalary(other.getSalary());
      }
      if (departmentBuilder_ == null) {
        if (!other.department_.isEmpty()) {
          if (department_.isEmpty()) {
            department_ = other.department_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureDepartmentIsMutable();
            department_.addAll(other.department_);
          }
          onChanged();
        }
      } else {
        if (!other.department_.isEmpty()) {
          if (departmentBuilder_.isEmpty()) {
            departmentBuilder_.dispose();
            departmentBuilder_ = null;
            department_ = other.department_;
            bitField0_ = (bitField0_ & ~0x00000001);
            departmentBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getDepartmentFieldBuilder() : null;
          } else {
            departmentBuilder_.addAllMessages(other.department_);
          }
        }
      }
      internalGetMutableAddressmap().mergeFrom(
          other.internalGetAddressmap());
      if (other.getInactive() != false) {
        setInactive(other.getInactive());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.java.GeneratedClasses.Employee parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.java.GeneratedClasses.Employee) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private int id_ ;
    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public int getId() {
      return id_;
    }
    /**
     * <code>int32 id = 1;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(int value) {
      
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      
      id_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object name_ = "";
    /**
     * <code>string name = 2;</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string name = 2;</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      name_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string name = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      
      name_ = getDefaultInstance().getName();
      onChanged();
      return this;
    }
    /**
     * <code>string name = 2;</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      name_ = value;
      onChanged();
      return this;
    }

    private double salary_ ;
    /**
     * <code>double salary = 3;</code>
     * @return The salary.
     */
    @java.lang.Override
    public double getSalary() {
      return salary_;
    }
    /**
     * <code>double salary = 3;</code>
     * @param value The salary to set.
     * @return This builder for chaining.
     */
    public Builder setSalary(double value) {
      
      salary_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double salary = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearSalary() {
      
      salary_ = 0D;
      onChanged();
      return this;
    }

    private java.util.List<com.java.GeneratedClasses.Department> department_ =
      java.util.Collections.emptyList();
    private void ensureDepartmentIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        department_ = new java.util.ArrayList<com.java.GeneratedClasses.Department>(department_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.java.GeneratedClasses.Department, com.java.GeneratedClasses.Department.Builder, com.java.GeneratedClasses.DepartmentOrBuilder> departmentBuilder_;

    /**
     * <code>repeated .com.java.Department department = 4;</code>
     */
    public java.util.List<com.java.GeneratedClasses.Department> getDepartmentList() {
      if (departmentBuilder_ == null) {
        return java.util.Collections.unmodifiableList(department_);
      } else {
        return departmentBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .com.java.Department department = 4;</code>
     */
    public int getDepartmentCount() {
      if (departmentBuilder_ == null) {
        return department_.size();
      } else {
        return departmentBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .com.java.Department department = 4;</code>
     */
    public com.java.GeneratedClasses.Department getDepartment(int index) {
      if (departmentBuilder_ == null) {
        return department_.get(index);
      } else {
        return departmentBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .com.java.Department department = 4;</code>
     */
    public Builder setDepartment(
        int index, com.java.GeneratedClasses.Department value) {
      if (departmentBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDepartmentIsMutable();
        department_.set(index, value);
        onChanged();
      } else {
        departmentBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.java.Department department = 4;</code>
     */
    public Builder setDepartment(
        int index, com.java.GeneratedClasses.Department.Builder builderForValue) {
      if (departmentBuilder_ == null) {
        ensureDepartmentIsMutable();
        department_.set(index, builderForValue.build());
        onChanged();
      } else {
        departmentBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.java.Department department = 4;</code>
     */
    public Builder addDepartment(com.java.GeneratedClasses.Department value) {
      if (departmentBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDepartmentIsMutable();
        department_.add(value);
        onChanged();
      } else {
        departmentBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .com.java.Department department = 4;</code>
     */
    public Builder addDepartment(
        int index, com.java.GeneratedClasses.Department value) {
      if (departmentBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDepartmentIsMutable();
        department_.add(index, value);
        onChanged();
      } else {
        departmentBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.java.Department department = 4;</code>
     */
    public Builder addDepartment(
        com.java.GeneratedClasses.Department.Builder builderForValue) {
      if (departmentBuilder_ == null) {
        ensureDepartmentIsMutable();
        department_.add(builderForValue.build());
        onChanged();
      } else {
        departmentBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.java.Department department = 4;</code>
     */
    public Builder addDepartment(
        int index, com.java.GeneratedClasses.Department.Builder builderForValue) {
      if (departmentBuilder_ == null) {
        ensureDepartmentIsMutable();
        department_.add(index, builderForValue.build());
        onChanged();
      } else {
        departmentBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.java.Department department = 4;</code>
     */
    public Builder addAllDepartment(
        java.lang.Iterable<? extends com.java.GeneratedClasses.Department> values) {
      if (departmentBuilder_ == null) {
        ensureDepartmentIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, department_);
        onChanged();
      } else {
        departmentBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .com.java.Department department = 4;</code>
     */
    public Builder clearDepartment() {
      if (departmentBuilder_ == null) {
        department_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        departmentBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .com.java.Department department = 4;</code>
     */
    public Builder removeDepartment(int index) {
      if (departmentBuilder_ == null) {
        ensureDepartmentIsMutable();
        department_.remove(index);
        onChanged();
      } else {
        departmentBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .com.java.Department department = 4;</code>
     */
    public com.java.GeneratedClasses.Department.Builder getDepartmentBuilder(
        int index) {
      return getDepartmentFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .com.java.Department department = 4;</code>
     */
    public com.java.GeneratedClasses.DepartmentOrBuilder getDepartmentOrBuilder(
        int index) {
      if (departmentBuilder_ == null) {
        return department_.get(index);  } else {
        return departmentBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .com.java.Department department = 4;</code>
     */
    public java.util.List<? extends com.java.GeneratedClasses.DepartmentOrBuilder> 
         getDepartmentOrBuilderList() {
      if (departmentBuilder_ != null) {
        return departmentBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(department_);
      }
    }
    /**
     * <code>repeated .com.java.Department department = 4;</code>
     */
    public com.java.GeneratedClasses.Department.Builder addDepartmentBuilder() {
      return getDepartmentFieldBuilder().addBuilder(
          com.java.GeneratedClasses.Department.getDefaultInstance());
    }
    /**
     * <code>repeated .com.java.Department department = 4;</code>
     */
    public com.java.GeneratedClasses.Department.Builder addDepartmentBuilder(
        int index) {
      return getDepartmentFieldBuilder().addBuilder(
          index, com.java.GeneratedClasses.Department.getDefaultInstance());
    }
    /**
     * <code>repeated .com.java.Department department = 4;</code>
     */
    public java.util.List<com.java.GeneratedClasses.Department.Builder> 
         getDepartmentBuilderList() {
      return getDepartmentFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.java.GeneratedClasses.Department, com.java.GeneratedClasses.Department.Builder, com.java.GeneratedClasses.DepartmentOrBuilder> 
        getDepartmentFieldBuilder() {
      if (departmentBuilder_ == null) {
        departmentBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.java.GeneratedClasses.Department, com.java.GeneratedClasses.Department.Builder, com.java.GeneratedClasses.DepartmentOrBuilder>(
                department_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        department_ = null;
      }
      return departmentBuilder_;
    }

    private com.google.protobuf.MapField<
        java.lang.String, java.lang.String> addressmap_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetAddressmap() {
      if (addressmap_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            AddressmapDefaultEntryHolder.defaultEntry);
      }
      return addressmap_;
    }
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetMutableAddressmap() {
      onChanged();;
      if (addressmap_ == null) {
        addressmap_ = com.google.protobuf.MapField.newMapField(
            AddressmapDefaultEntryHolder.defaultEntry);
      }
      if (!addressmap_.isMutable()) {
        addressmap_ = addressmap_.copy();
      }
      return addressmap_;
    }

    public int getAddressmapCount() {
      return internalGetAddressmap().getMap().size();
    }
    /**
     * <code>map&lt;string, string&gt; addressmap = 5;</code>
     */

    @java.lang.Override
    public boolean containsAddressmap(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetAddressmap().getMap().containsKey(key);
    }
    /**
     * Use {@link #getAddressmapMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getAddressmap() {
      return getAddressmapMap();
    }
    /**
     * <code>map&lt;string, string&gt; addressmap = 5;</code>
     */
    @java.lang.Override

    public java.util.Map<java.lang.String, java.lang.String> getAddressmapMap() {
      return internalGetAddressmap().getMap();
    }
    /**
     * <code>map&lt;string, string&gt; addressmap = 5;</code>
     */
    @java.lang.Override

    public java.lang.String getAddressmapOrDefault(
        java.lang.String key,
        java.lang.String defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetAddressmap().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, string&gt; addressmap = 5;</code>
     */
    @java.lang.Override

    public java.lang.String getAddressmapOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetAddressmap().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public Builder clearAddressmap() {
      internalGetMutableAddressmap().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <code>map&lt;string, string&gt; addressmap = 5;</code>
     */

    public Builder removeAddressmap(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      internalGetMutableAddressmap().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String>
    getMutableAddressmap() {
      return internalGetMutableAddressmap().getMutableMap();
    }
    /**
     * <code>map&lt;string, string&gt; addressmap = 5;</code>
     */
    public Builder putAddressmap(
        java.lang.String key,
        java.lang.String value) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      if (value == null) { throw new java.lang.NullPointerException(); }
      internalGetMutableAddressmap().getMutableMap()
          .put(key, value);
      return this;
    }
    /**
     * <code>map&lt;string, string&gt; addressmap = 5;</code>
     */

    public Builder putAllAddressmap(
        java.util.Map<java.lang.String, java.lang.String> values) {
      internalGetMutableAddressmap().getMutableMap()
          .putAll(values);
      return this;
    }

    private boolean inactive_ ;
    /**
     * <pre>
     *bytes profilePicture=7;
     *google.protobuf.Timestamp joindate=8;
     * </pre>
     *
     * <code>bool inactive = 6;</code>
     * @return The inactive.
     */
    @java.lang.Override
    public boolean getInactive() {
      return inactive_;
    }
    /**
     * <pre>
     *bytes profilePicture=7;
     *google.protobuf.Timestamp joindate=8;
     * </pre>
     *
     * <code>bool inactive = 6;</code>
     * @param value The inactive to set.
     * @return This builder for chaining.
     */
    public Builder setInactive(boolean value) {
      
      inactive_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *bytes profilePicture=7;
     *google.protobuf.Timestamp joindate=8;
     * </pre>
     *
     * <code>bool inactive = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearInactive() {
      
      inactive_ = false;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.java.Employee)
  }

  // @@protoc_insertion_point(class_scope:com.java.Employee)
  private static final com.java.GeneratedClasses.Employee DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.java.GeneratedClasses.Employee();
  }

  public static com.java.GeneratedClasses.Employee getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Employee>
      PARSER = new com.google.protobuf.AbstractParser<Employee>() {
    @java.lang.Override
    public Employee parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Employee(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Employee> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Employee> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.java.GeneratedClasses.Employee getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

