// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: employee.proto

package com.java.GeneratedClasses;

public interface EmployeeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.java.Employee)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   * @return The id.
   */
  int getId();

  /**
   * <code>string name = 2;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>double salary = 3;</code>
   * @return The salary.
   */
  double getSalary();

  /**
   * <code>repeated .com.java.Department department = 4;</code>
   */
  java.util.List<com.java.GeneratedClasses.Department> 
      getDepartmentList();
  /**
   * <code>repeated .com.java.Department department = 4;</code>
   */
  com.java.GeneratedClasses.Department getDepartment(int index);
  /**
   * <code>repeated .com.java.Department department = 4;</code>
   */
  int getDepartmentCount();
  /**
   * <code>repeated .com.java.Department department = 4;</code>
   */
  java.util.List<? extends com.java.GeneratedClasses.DepartmentOrBuilder> 
      getDepartmentOrBuilderList();
  /**
   * <code>repeated .com.java.Department department = 4;</code>
   */
  com.java.GeneratedClasses.DepartmentOrBuilder getDepartmentOrBuilder(
      int index);

  /**
   * <code>map&lt;string, string&gt; addressmap = 5;</code>
   */
  int getAddressmapCount();
  /**
   * <code>map&lt;string, string&gt; addressmap = 5;</code>
   */
  boolean containsAddressmap(
      java.lang.String key);
  /**
   * Use {@link #getAddressmapMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, java.lang.String>
  getAddressmap();
  /**
   * <code>map&lt;string, string&gt; addressmap = 5;</code>
   */
  java.util.Map<java.lang.String, java.lang.String>
  getAddressmapMap();
  /**
   * <code>map&lt;string, string&gt; addressmap = 5;</code>
   */

  java.lang.String getAddressmapOrDefault(
      java.lang.String key,
      java.lang.String defaultValue);
  /**
   * <code>map&lt;string, string&gt; addressmap = 5;</code>
   */

  java.lang.String getAddressmapOrThrow(
      java.lang.String key);

  /**
   * <pre>
   *bytes profilePicture=7;
   *google.protobuf.Timestamp joindate=8;
   * </pre>
   *
   * <code>bool inactive = 6;</code>
   * @return The inactive.
   */
  boolean getInactive();
}
