// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: employee.proto

package com.java.GeneratedClasses;

public interface EmployeeListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.java.EmployeeList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .com.java.Employee employees = 1;</code>
   */
  java.util.List<com.java.GeneratedClasses.Employee> 
      getEmployeesList();
  /**
   * <code>repeated .com.java.Employee employees = 1;</code>
   */
  com.java.GeneratedClasses.Employee getEmployees(int index);
  /**
   * <code>repeated .com.java.Employee employees = 1;</code>
   */
  int getEmployeesCount();
  /**
   * <code>repeated .com.java.Employee employees = 1;</code>
   */
  java.util.List<? extends com.java.GeneratedClasses.EmployeeOrBuilder> 
      getEmployeesOrBuilderList();
  /**
   * <code>repeated .com.java.Employee employees = 1;</code>
   */
  com.java.GeneratedClasses.EmployeeOrBuilder getEmployeesOrBuilder(
      int index);
}
