// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: employee.proto

package com.java.GeneratedClasses;

public final class EmployeeProto {
  private EmployeeProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_java_Employee_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_java_Employee_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_java_Employee_AddressmapEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_java_Employee_AddressmapEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_java_Department_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_java_Department_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_java_EmployeeList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_java_EmployeeList_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_java_Empty_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_java_Empty_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016employee.proto\022\010com.java\"\333\001\n\010Employee\022" +
      "\n\n\002id\030\001 \001(\005\022\014\n\004name\030\002 \001(\t\022\016\n\006salary\030\003 \001(" +
      "\001\022(\n\ndepartment\030\004 \003(\0132\024.com.java.Departm" +
      "ent\0226\n\naddressmap\030\005 \003(\0132\".com.java.Emplo" +
      "yee.AddressmapEntry\022\020\n\010inactive\030\006 \001(\010\0321\n" +
      "\017AddressmapEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002" +
      " \001(\t:\0028\001\"&\n\nDepartment\022\n\n\002id\030\001 \001(\005\022\014\n\004na" +
      "me\030\002 \001(\t\"5\n\014EmployeeList\022%\n\temployees\030\001 " +
      "\003(\0132\022.com.java.Employee\"\007\n\005Empty2\272\001\n\017Emp" +
      "loyeeService\0225\n\013getEmployee\022\022.com.java.E" +
      "mployee\032\022.com.java.Employee\0225\n\013addEmploy" +
      "ee\022\022.com.java.Employee\032\022.com.java.Employ" +
      "ee\0229\n\016getAllEmployee\022\017.com.java.Empty\032\026." +
      "com.java.EmployeeListB,\n\031com.java.Genera" +
      "tedClassesB\rEmployeeProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_java_Employee_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_java_Employee_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_java_Employee_descriptor,
        new java.lang.String[] { "Id", "Name", "Salary", "Department", "Addressmap", "Inactive", });
    internal_static_com_java_Employee_AddressmapEntry_descriptor =
      internal_static_com_java_Employee_descriptor.getNestedTypes().get(0);
    internal_static_com_java_Employee_AddressmapEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_java_Employee_AddressmapEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_com_java_Department_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_java_Department_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_java_Department_descriptor,
        new java.lang.String[] { "Id", "Name", });
    internal_static_com_java_EmployeeList_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_java_EmployeeList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_java_EmployeeList_descriptor,
        new java.lang.String[] { "Employees", });
    internal_static_com_java_Empty_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_java_Empty_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_java_Empty_descriptor,
        new java.lang.String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
