// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: employee.proto

package com.java.GeneratedClasses;

public interface EmptyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.java.Empty)
    com.google.protobuf.MessageOrBuilder {
}
